#!/bin/bash
#PBS -q romeq
#PBS -N LJ
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=64

module load  openmpi/mlnx/gcc/64/4.0.3rc4
cd $PBS_O_WORKDIR
pwd

folder=tj-alpha$alpha
mkdir $folder

mpirun -np 64  $HOME/mylammps/src/lmp_mpi -in in.lj-solute.lmp -v alpha ${alpha} -v folder ${folder}
